version: '3.5'
services:
  nodered:
    container_name: nodered
    image: nodered/node-red:latest-22
    ports:
      - 1880:1880
      - 6123:6123 # used for communicating via TCP on e2e tests
    volumes:
      - nodered_data:/data
      - ./data:/data

volumes:
  nodered_data: