name: Nodered - Complete Project

on:
  push:
    branches:
      - main
    paths:
      - '**.js'
      - '**.json'
      - '**.yml'
      - '**.sh'

jobs:
  setup-and-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Set up Docker Compose
      run: |
        sudo rm /usr/local/bin/docker-compose
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /tmp/docker-compose
        chmod +x /tmp/docker-compose
        sudo mv /tmp/docker-compose /usr/local/bin/docker-compose

    - name: Start nodered
      run: npm run docker:install-module

    - name: Restore dependencies
      run: npm ci

    - name: Install Chromium browser only
      run: npx playwright install chromium --with-deps

    - name: Run Playwright tests
      run: npm run playwright:headless

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Clean up
      run: docker-compose down --volumes