name: Nodered - Complete Project

on:
  push:
    branches:
      - main
    paths:
      - '**.js'
      - '**.json'
      - '**.yml'

jobs:
  setup-and-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        node-version: lts/*

    - name: Set up Docker Compose
      run: |
        sudo rm /usr/local/bin/docker-compose
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /tmp/docker-compose
        chmod +x /tmp/docker-compose
        sudo mv /tmp/docker-compose /usr/local/bin/docker-compose

    - run: npm ci

    - name: Start nodered
      run: npm run docker:install-module

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Clean up
      run: docker-compose down